[workspace]
members = ["dist:."]

# Config for 'dist'
[dist]

# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0"

# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = false

# System dependencies for different platforms
[dist.dependencies.apt]
"libgtk-3-dev" = "*"
"libsoup2.4-dev" = "*"
"libwebkit2gtk-4.0-dev" = "*"
"libjavascriptcoregtk-4.0-dev" = "*"
"libudev-dev" = "*"
"libxdo-dev" = "*"
"pkg-config" = "*"
